volumes:
  postgres:

networks:
  backend:

services:
  postgres:
    image: postgres:14
    volumes:
    - postgres:/var/lib/postgresql/data:rw
    networks:
      backend:
        aliases:
        - postgres
    env_file:
    - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "$POSTGRES_DB", "-U", "$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 2
