name: Ansible Lint Check

on:
  push:
    paths:
      - '*.yml'

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@v1
      with:
        ansible-lint-path: install.yml
