name: Ansible Lint Check

on:
  push:
    branches:
      - master

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@v1
      with:
        ansible-lint-path: playbook.yml
    - name: Notify Slack
      uses: slack-action/slack@v1
      with:
        args: Success
      if: success()
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
